
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

#for the stupid tuya blinds
zha:
  custom_quirks_path: /config/custom_zha_quirks


# for version controlled dashboard
lovelace:
  mode: storage
  dashboards:
    our-home-v2:
      mode: yaml
      title: Our Home V2
      icon: mdi:home
      show_in_sidebar: true
      filename: dashboards/our_home_v2.yaml